language: python
python:
- '3.4'
sudo: false
install:
- pip install -e git+https://github.com/deconst/preparer-sphinx.git#egg=deconstrst
script:
- script/cibuild
env:
  global:
  - secure: q5fPGShpXtm6NjddzU0gvZl8mdyVbAC8P9jddnL6L31ezV0Sr0p78Pm7GFF+b4KYcMJid3kCz6VFu9gAss35KC8Tc5ie1QiCFL1MDdkbjJDeAbGtUB0cUjZGEcAR0fJ/r4kc4vcZahtpyDdQkCSgODLRs8hkxW04SJW8/vXhtzk=
  - secure: ABq9/qC4/BPpxmBPw4ek91Xp1XgVzOvQvc/9h0EzQOyj/nmISzAjToGz55Ps2wTGufnNjxbdA9EeRIIbJwe2/4agXOGB7LmukoyqDZbZ/wayrorodlOuxYjztJnIO4cYKzHkpJTguMZWb8d7ah20PKZLpUadyaGkjCIi2rtwhqY=
  - secure: wrAgW2pHdUW4YsauT8WYA9crA1emhh1JvPjGQfIyEQjOxDKP5yEC5Wk7DE3yEHgghsLebt9MAlz2VktrCCqZog8Tzj4InrNZBPAYSzjCmW/UKnY9s8FH7SNGG7I3G95XUGTtHPJ5bu8OKEivnsWzpckmJwYfObTHJF02FmBdhsc=
notifications:
  slack:
    secure: Nb647YGWA40As8hl8K/bu82wZCzuQ4oSb+KDBylMfB11kXsypY+nVzmsKU/ePL5Bi28/+4S94DdD0mZYpib8iDSBft9KRfz5TJAN70Hbrdj13J/m/5QUtDFdQH8FEHIuDQWWBPQYXh3rXvarmGCmcu9duUXVb8kJT+prY+B8dFM=
